### ISSUE TITLE
Add Contributing.md

### ISSUE THREAD

**Issue by Chirag-Mathur** [Chirag-Mathur/hello-world#32]
Add basic common guidelines to contribute to this repo.
Do add that code should be complete and proper snapshots should be added showing the working of the code.

**Comment by Mayankjha997** [comment]
I want to contribute in c language

**Comment by Chirag-Mathur** [comment]
@Mayankjha997 You can contribute in any language you want, Just create the issue on the program u want to add when assigned send the PR of that.

**Comment by Chirag-Mathur** [comment]
@Mayankjha997 This issue is specific to add the contributing.md file. Please stick to that.
