### ISSUE TITLE
Add Grakn Forces Folder

### ISSUE THREAD

**Issue by Chirag-Mathur** [Chirag-Mathur/hello-world#33]
Add a folder of [Grakin Forces](https://codeforces.com/contest/1408) to put the solutions of this contest in this folder.

**Comment by priyanshupardhi** [comment]
Hey @Chirag-Mathur , I am working on it

**Comment by Chirag-Mathur** [comment]
@priyanshupardhi GFI 👍

**Comment by vibalijoshi** [comment]
So need to write the solutions too?

**Comment by Chirag-Mathur** [comment]
@vibalijoshi  No, just a folder. Solutions will be covered in a separate issue.
You can create an issue for that if you want 😄 .

**Comment by vibalijoshi** [comment]
okay late now XD
