### ISSUE TITLE
Add GraknForces Remaining Solutions

### ISSUE THREAD

**Issue by Chirag-Mathur** [Chirag-Mathur/hello-world#43]
Add [GraknForces](https://codeforces.com/graknforces) remaining solutions to [this folder](https://github.com/Chirag-Mathur/hello-world/tree/master/GrakinForces)

**Comment by imakshat01** [comment]
I have solved the B problem and made a PR

**Comment by imakshat01** [comment]
I have  added C problem . Please check.
