### ISSUE TITLE
Add CF Round 672 Div 2 Solutions.

### ISSUE THREAD

**Issue by Chirag-Mathur** [Chirag-Mathur/hello-world#54]
Add [cfRound670d2](https://codeforces.com/contest/1406) solutions to [this folder](https://github.com/Chirag-Mathur/hello-world/tree/master/cfRound670d2)

**Comment by Tripathi-Alok** [comment]
Please assign this to me Sir

**Comment by Chirag-Mathur** [comment]
@Tripathi-Alok Start submitting solutions of the questions with proper snapshots, I will merge them.
No need to assign this issue.
