### ISSUE TITLE
Adding Leetcode Biweekly Contest 62 [C++]

### ISSUE THREAD

**Issue by Chirag-Mathur** [Chirag-Mathur/hello-world#72]
[Link to the Contest](https://leetcode.com/contest/biweekly-contest-62)

**Comment by Harsh-Modi278** [comment]
Hi @Chirag-Mathur , can you please assign this issue to me? I would like to add [Q1](https://leetcode.com/contest/biweekly-contest-62/problems/convert-1d-array-into-2d-array/), [Q2](https://leetcode.com/contest/biweekly-contest-62/problems/number-of-pairs-of-strings-with-concatenation-equal-to-target/) and [Q3](https://leetcode.com/contest/biweekly-contest-62/problems/maximize-the-confusion-of-an-exam/) of [LeetCode Biweekly contest 62](https://leetcode.com/contest/biweekly-contest-62/) in C++ as a hacktoberfest participant.

**Comment by Chirag-Mathur** [comment]
GFI @Harsh-Modi278
